Popup window
johnkioko/My-Portofolio-Project pull request #12
Opened 2022-09-09 18:12 UTC by johnkioko

**### You should implement the following interactions:**

1.Implemented popup window that pops when the user clicks (or taps) the button to check project details, the with details about the project appears.

2. When the user clicks (or taps) the close (X) button, the popup disappears.
In order to associate each project with the popup window details, you must refactor the project section:

2022-09-09 18:52 UTC, RolandM99 requested changes
Hi  @johnkioko , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 18:52 UTC, RolandM99 commented on popup.css
> +
- [ ] Kindly, make sure that your design for the popup window for the mobile version looks exactly like the original design from Figma.
take a look at the table below:

|Figma Design|Your Design|
|---------------|-------------|
|![image](https://user-images.githubusercontent.com/71874425/189421941-6e6ad77e-098d-4d13-b8d1-824e1845844e.png)|![image](https://user-images.githubusercontent.com/71874425/189422247-fd384011-10ed-408e-aad9-8983e9f1520f.png)|

2022-09-09 21:58 UTC, rotimiazeez requested changes
# Hi @johnkioko 👍🏽 , 
## You're almost done here 🤏🏽 
### Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-09-09 21:58 UTC, rotimiazeez commented on index.html
> +    </section>
- Please note that the icons on your page are broken, kindly fix them. 👍🏽
![Screenshot from 2022-09-09 22-45-13](https://user-images.githubusercontent.com/44624138/189450852-7aa8c62d-6fc7-4701-b3c7-7d699124c919.png)
![Screenshot from 2022-09-09 22-44-11](https://user-images.githubusercontent.com/44624138/189450863-59c8c298-2759-4753-9566-6db2631a02c8.png)

2022-09-09 21:58 UTC, rotimiazeez commented on index.html
> +    </section>
- Please be sure your design matches the original Figma design for a better User Interface(UI) 😉.
Your Design | Figma Design
![Screenshot from 2022-09-09 22-45-13](https://user-images.githubusercontent.com/44624138/189451142-c20b816b-5718-4179-84e1-9ef1a242f3b3.png) | ![Screenshot from 2022-09-09 22-48-12](https://user-images.githubusercontent.com/44624138/189451144-c854ca14-c0ea-4249-8a8e-dbf337c55def.png)

2022-09-10 00:05 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @johnkioko , 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive PR.
:heavy_check_mark: Well implemented suggested changes.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "Fixed bug".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-09-10 08:07 UTC, merged