New feature desktop version
johnkioko/My-Portofolio-Project pull request #5
Opened 2022-08-25 13:20 UTC by johnkioko

Desktop version of the Portfolio:

1.Add the html for the desktop version of the portfolio
2.Added styles for the desktop version
3. Added media query to make the desktop version responsive

2022-08-25 16:05 UTC, KayLemba requested changes
Hi @ElsonOtake   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.
Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-25 16:05 UTC, KayLemba commented on index.html
> -  </section>
While you did a good job implementing the desktop version of you portfolio. it would be nice if you removed the horizontal scroll from your page for it is making your page content not look centered. Your page should only scroll up and down not left and right. Your  page has to be fixed without a scroll from left to right.

Here is is what you need to remove from your page:
![john desk2](https://user-images.githubusercontent.com/79506105/186702547-d01d06b3-88ea-4237-b980-a9c46558d726.png)

2022-08-25 16:05 UTC, KayLemba commented on index.html
> +
1. When I switch to your mobile version I noticed Your page content in the my recent work section is leaning too  much on the left. Your page content is supposed to be centered. Your can fix this by adding a padding-left to  help you adjust the content and centering it.

2. I also noticed a blank space after the my recent works title Im pretty sure  your work section shpuld 
    appear after this title please fix this. 

This is your design:

 
![jon mobile1](https://user-images.githubusercontent.com/79506105/186712211-7f989051-bdd7-4738-a446-36718f1ecf6e.png)
Please kindly stick to the figma design.

Follow this design:
![mobile2](https://user-images.githubusercontent.com/79506105/186712422-e9913ede-7e2d-4f86-a355-e4c7902e8246.png)

2022-08-25 16:05 UTC, KayLemba commented on index.html
>    </div>
The same applies here in your work section were you are displaying your cards. The page content in this section is also leaning too much on the left it has to be centered as well you also fix this issue by adding a padding left as well .

This is your design:
![jon mobile 3](https://user-images.githubusercontent.com/79506105/186713994-75d5a527-f3de-49c7-8604-93267f7a248c.png)

Please stick to ths figma design:

![mobile3](https://user-images.githubusercontent.com/79506105/186714186-320d95e4-3239-4e6b-9503-23179b476210.png)

2022-08-26 08:38 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @johnkioko  , I'm @MaganaAsiati , your reviewer for this PR  :wave: 
Great work on making the changes requested by a previous reviewer 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>


## Highlights
- Descriptive pull request :heavy_check_mark:👨🏻‍💻
- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] Check the comments under the review.



Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Cheers and Happy coding! 🤓 👏👏👏

2022-08-26 08:50 UTC, merged